FROM node:20-alpine

WORKDIR /app

ARG SUPABASE_URL
ARG SUPABASE_SERVICE_KEY
ARG OPENROUTER_API_KEY
ARG OPENROUTER_VISION_MODEL=anthropic/claude-sonnet-4-20250514
ARG OPENROUTER_EMBEDDING_MODEL=text-embedding-3-small
ARG PORT=3000

ENV SUPABASE_URL=$SUPABASE_URL
ENV SUPABASE_SERVICE_KEY=$SUPABASE_SERVICE_KEY
ENV OPENROUTER_API_KEY=$OPENROUTER_API_KEY
ENV OPENROUTER_VISION_MODEL=$OPENROUTER_VISION_MODEL
ENV OPENROUTER_EMBEDDING_MODEL=$OPENROUTER_EMBEDDING_MODEL
ENV PORT=$PORT

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]
